# action.yml
name: 'kata-deploy-aks'
description: 'test Kata container image in AKS'
inputs:
  container_image:
    description: 'Kata deploy image to use'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.container_image }}
