name: kata-deploy-build

# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]
  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-asset:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        asset:
          - kernel
          - shim-v2
          - qemu
          - cloud-hypervisor
          - firecracker
          - guest-image
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
        env:
          KATA_ASSET: ${{ matrix.asset }}
          TAR_OUTPUT: "kata-${{ matrix.asset }}.tar.gz"

      - name: Build kata-deploy-builder
        run: ./tools/packaging/kata-deploy/builder/scripts/docker-build.sh

      - name: Build ${{ matrix.asset }}
        run: ./kata-deploy-builder build --tar-output "${TAR_OUTPUT}" "${KATA_ASSET}"

      - name: store-artifact ${KATA_ASSET} ${TAR_OUTPUT}
        uses: actions/upload-artifact@v2
        with:
          name: kata-artifacts
          path: ${TAR_OUTPUT}
  create-kata-tarball:
    runs-on: ubuntu-latest
    needs: build-asset
    steps:
      - uses: actions/checkout@v2
      - name: get-artifacts
        uses: actions/download-artifact@v2
        with:
          name: kata-artifacts
          path: kata-artifacts
      - name: colate-artifacts
        run: |
          $GITHUB_WORKSPACE/.github/workflows/gather-artifacts.sh
      - name: store-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-candidate
          path: kata-static.tar.xz
