name: build image
on: 
  push:
    branches:
      - master

jobs:
  # Job for building the image
  build-image:
    runs-on: ubuntu-18.04
    env:
      osbuilder_repo: "github.com/kata-containers/osbuilder"
      agent_repo: "github.com/kata-containers/agent"
      agent_pr: "pull/706/head"
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.12.3'
      - name: Set GOPATH
        run: |
          export GOPATH="${HOME}/go"
          echo "##[set-env name=GOPATH;]${GOPATH}"
          echo "##[add-path]${GOPATH}/bin"
          mkdir -p "${GOPATH}/bin"
      - name: Install yq
        run: |
          curl -o "${GOPATH}/bin/yq" -LSsf https://github.com/mikefarah/yq/releases/download/2.3.0/yq_linux_amd64
          chmod +x "$GOPATH/bin/yq"
      - name: install hub
        run: |
          HUB_VER=$(curl -s "https://api.github.com/repos/github/hub/releases/latest" | jq -r .tag_name | sed 's/^v//')
          wget -q -O- https://github.com/github/hub/releases/download/v$HUB_VER/hub-linux-amd64-$HUB_VER.tgz | \
          tar xz --strip-components=2 --wildcards '*/bin/hub' && sudo mv hub /usr/local/bin/hub
      - name: checkout to agent version
        run: |
          go get "${agent_repo}" || true
          pushd "${GOPATH}/src/${agent_repo}"
          git fetch origin ${agent_pr}:TARGET
          git checkout TARGET
          popd
      - name: build image
        run: |
          go get "${osbuilder_repo}" || true
          pushd "${GOPATH}/src/${osbuilder_repo}"
          sudo -E PATH="${PATH}" make image DISTRO="clearlinux" DEBUG="1" USE_DOCKER="1" ROOTFS_BUILD_DEST="/tmp/rootfs-image" GO_VERSION=1.12.3
          popd
      - name: push image to github
        run: |
          set -x
          agent_version=$("${GOPATH}/src/${agent_repo}/kata-agent" --version | awk '{print $3}')
          kata_image_path="${PWD}/kata-agent-${agent_version}.img"
          mv "${GOPATH}/src/${osbuilder_repo}/kata-containers.img" "${kata_image_path}"
          pwd
          GITHUB_TOKEN=${{ secrets.GIT_UPLOAD_TOKEN }} hub release edit -m "" -a "${kata_image_path}" "prueba"
