name: build image
on: 
  push: 
    tags:
     - '*'

jobs:
  # Job for building the image
  build-image:
    runs-on: ubuntu-18.04
    steps:
      - name: build-image
        run: |
         git clone https://github.com/kata-containers/packaging.git
         cd packaging
         ./obs-packaging/kata-containers-image/build_image.sh
