name: build image
on: 
  push:
    branches:
      - master

jobs:
  # Job for building the image
  build-image:
    runs-on: ubuntu-18.04
    env:
      osbuilder_url: "https://github.com/kata-containers/osbuilder.git"
    steps:
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.12.3'
      - name: build
        run: |
          set -x
          echo "GOPATH=$GOPATH"
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$PATH
          echo "GOPATH=$GOPATH"
          mkdir -p $GOPATH/bin
          curl -o $GOPATH/bin/yq -LSsf https://github.com/mikefarah/yq/releases/download/2.3.0/yq_linux_amd64
          chmod +x $GOPATH/bin/yq
          git clone "$osbuilder_url" "osbuilder"
          go get github.com/kata-containers/agent
          pushd ${GOPATH}/src/github.com/kata-containers/agent
          git fetch origin pull/706/head:PR
          git checkout PR
          popd
          cd osbuilder
          sudo -E PATH="${PATH}" make image DISTRO="clearlinux" DEBUG="1" USE_DOCKER="1" IMG_OS_VERSION="${img_os_version}" ROOTFS_BUILD_DEST="${tmp_dir}/rootfs-image" GO_VERSION=1.12.3
